Repository GSG-G11/Quran-App, pull requests merged in 2022-02, with the labels that each got.

#2 add structure files
  css/all.min.css
  css/main.css
  img/favicon.ico
  index.html
  js/index.js
  webfonts/fa-brands-400.eot
  webfonts/fa-brands-400.svg
  webfonts/fa-brands-400.ttf
  webfonts/fa-brands-400.woff
  webfonts/fa-brands-400.woff2
  webfonts/fa-regular-400.eot
  webfonts/fa-regular-400.svg
  webfonts/fa-regular-400.ttf
  webfonts/fa-regular-400.woff
  webfonts/fa-regular-400.woff2
  webfonts/fa-solid-900.eot
  webfonts/fa-solid-900.svg
  webfonts/fa-solid-900.ttf
  webfonts/fa-solid-900.woff
  webfonts/fa-solid-900.woff2
Labels: Awaiting Review

#6 Create header for main page
  css/main.css
  img/favicon.ico
  img/header.jpg
  img/logo.png
  index.html
Labels: Awaiting Review

#5 finish of create div surah
  .vscode/settings.json
  css/main.css
  index.html
Labels: Awaiting Review

#9 finishing of rendering box
  css/main.css
  js/index.js
Labels: Awaiting Review

#10 coding details page with javascript
  css/details.css
  css/main.css
  details.html
  img/logo.png
  index.html
  js/details.js
  js/dom.js
Labels: Awaiting Review

#12 update some codes
  css/details.css
  css/main.css
  details.html
  index.html
  js/details.js
  js/dom.js
Labels: Awaiting Review

#13 fix some code
  css/main.css
  index.html
  js/index.js
Labels: In Progress

#15 make website responsive
  css/details.css
  css/main.css
  index.html
  js/details.js
  js/dom.js
  js/index.js
Labels: Done
